api/views.py
import json
import os
import settings
import utils
from flask import (
    Blueprint,
    current_app,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    url_for,
)
from middleware import model_predict


from flask_socketio import SocketIO, emit
from engineio.payload import Payload



Payload.max_decode_packets = 2048


router = Blueprint("app_router", __name__, template_folder="templates")

@router.route("/new_prediction", methods=["GET"])
def new_upload():
  # context = {
  #             'models' : settings.AVAILABLE_MODELS
  #           }
  #return render_template("index.html", context=context, scroll="upload_image")
  return render_template("index.html",  scroll="upload_image")




@router.route("/", methods=["GET", "POST"])
def index():
    """
    GET: Index endpoint, renders our HTML code.

    POST: Used in our frontend so we can upload and show an image.
    When it receives an image from the UI, it also calls our ML model to
    get and display the predictions.
    """
    
    if request.method == "GET":
        return render_template("index.html")

    if request.method == "POST":
        print('POST')
        # No file received, show basic UI
        if "file" not in request.files:
            flash("No file part")
            return redirect(request.url)
        print('file in request.files')

        # File received but no filename is provided, show basic UI
        file = request.files["file"]
        if file.filename == "":
            flash("No image selected for uploading")
            return redirect(request.url)
        print(file.filename)

        # File received and it's an image, we must show it and get predictions
        if file and utils.allowed_file(file.filename):
            print('file allowed')
            # Creates unique name
            img_name = utils.get_file_hash(file)
            img_path = os.path.join(settings.UPLOAD_FOLDER,img_name)
            
            # Stores image in 'static\uploads'
            print('PATH:' , img_path)
            file.save(img_path)
            file.close()
            if 'rbtn_output_selection' in request.form:
              annotation_style = request.form['rbtn_output_selection']
              print(annotation_style)
            else:
              flash("** Please select an annotation style")
              return redirect(request.url+"#upload_image")

            if "heuristic" in request.form:
              show_heuristic = True
            else:
              show_heuristic = False
            
            print(request.form)
            print(img_name)
            print(annotation_style)

            # Sent image to be processed by the ML model
            is_streaming = False
            mAP = model_predict(img_name, is_streaming, annotation_style, show_heuristic)
        
            # Updates context
            context = {
                    "mAP": mAP,
                    "filename": img_path,
                    "annotation_style": annotation_style,
                    "show_heuristic": show_heuristic
                    }
            
            # Update `render_template()` parameters as needed 
            return render_template("index.html", filename=img_name, context=context)
        # File received and but it isn't an image
        else:
            flash("Allowed image types are -> png, jpg, jpeg, gif")
            return redirect(request.url)


@router.route("/display/<filename>")
def display_image(filename):
    """
    Display image uploaded.
    """
    return redirect(url_for("static", filename="uploads/" + filename))

@router.route("/display_bbox/<filename>")
def display_bbox(filename):
    """
    Display image predicted by the model in our UI.
    """
    basename, extension = os.path.splitext(filename)
    filename2 = basename + "_bbox" + extension

    return redirect(url_for("static", filename="predictions/" + filename2))

@router.route("/display_heatmap/<filename>")
def display_heatmap(filename):
    """
    Display image predicted by the model in our UI.
    """
    basename, extension = os.path.splitext(filename)
    filename2 = basename + "_heat" + extension

    return redirect(url_for("static", filename="predictions/" + filename2))

@router.route("/display_heuristic/<filename>")
def display_heuristic(filename):
    """
    Display image predicted by the model in our UI.
    """
    basename, extension = os.path.splitext(filename)
    filename2 = basename + "_heur" + extension

    return redirect(url_for("static", filename="predictions/" + filename2))

@router.route("/display_stream")
def display_stream():
    """
    Display image predicted by the model in our UI.
    """

    return redirect(url_for("static", filename="predictions/readb64.jpg"))

@router.route("/predict", methods=["GET", "POST"])
def predict(file = None):
    """
    Endpoint used to get predictions without need to access the UI.

    Parameters
    ----------
    file : str
        Input image we want to get predictions from.

    Returns
    -------
    flask.Response
        JSON response from our API having the following format:
            {
                "success": bool,
                "prediction": str,
                "score": float,
            }

        - "success" will be True if the input file is valid and we get a
          prediction from our ML model.
        - "prediction" model predicted class as string.
        - "score" model confidence score for the predicted class as float.
    """
    
    response_data = {"success": False, "prediction": None, "score": None} 
    status_code = 400
     
    if request.method == "GET":  
        status_code = 405
        
    elif request.method == "POST":
        
        # Check for file received 
        if "file" in request.files: file = request.files['file']
        
        # File received and it's an image, we must show it and get predictions
        if file and utils.allowed_file(file.filename):
            
            # 1. Creates unique name
            img_name = utils.get_file_hash(file)
            img_path = os.path.join(settings.UPLOAD_FOLDER,img_name)
            # 2. Stores image in '\upload'
            file.save(img_path)
            
            # 3. Sents image to be processed by the ML model
            prediction, score = model_predict(img_name)
            
            # 4. Updates Response
            response_data  = {"success": True, "prediction": prediction, "score": score}
            status_code = 200
            
            # checks for BottleNeck response
            if prediction == 'BottleNeck': 
                response_data  = {"success": False, "prediction": prediction, "score": score}
                status_code = 400
            
        # File received but it isn't an image
        else:
            flash("Allowed image types are -> png, jpg, jpeg, gif") 
            # rpse = current_app.response_class( response = json.dumps(data), status = 400, mimetype = 'application/json')    # Instead of: rpse = {"Error": 'HTTP Bad Request', "status_code": 400, "prediction": None, "score": None}
        
    return current_app.response_class( response = json.dumps(response_data), status = status_code, mimetype = settings.RPSE_MIMETYPE) 
    


@router.route("/feedback", methods=["GET", "POST"])
def feedback():
    """
    Store feedback from users about wrong predictions on a plain text file.

    Parameters
    ----------
    report : request.form
        Feedback given by the user with the following JSON format:
            {
                "filename": str,
                "prediction": str,
                "score": float
            }

        - "filename" corresponds to the image used stored in the uploads
          folder.
        - "prediction" is the model predicted class as string reported as
          incorrect.
        - "score" model confidence score for the predicted class as float.
    """
    # Get report 
    if request.method == "GET": 
        report_str = request.form.get("report")
        
    elif request.method == "POST":
        
        report_str = request.form.get("report")
        if report_str:
            report_path = settings.FEEDBACK_FILEPATH
            with open(report_path, 'a') as f:
                f.write(report_str+'\n')

    return render_template("index.html")

api/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      name="description"
      content="Frontend for Retail Store Object Detection."
    />
    <title>Retail Store Object Detection</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='web/styles/style.css') }}"
    />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.0.5/socket.io.min.js'></script>
    
  </head>

  <body>
    <header>
    </header>

    <hr style="margin-inline: -10px" />

    <section>
      <h1 id="title">Retail Store Object Detection</h1>

      {% if not filename %}

      <form method="post" action="/" enctype="multipart/form-data">
  
        <input type="file" id="uploaded_img" name="file" class="hidden" required>
        <div >Select an image to 
        <label for="uploaded_img" class="label_button"><u> Upload</u></label> </div>
        <br>

        <div id="form_detect">

          <div class="img_container">
            <img class="output_img" id="my_preview" />
          </div>
          
          <div class="form__group">
            <div>
              <input type="checkbox" id="heuristic" name="heuristic" value="True">
              <label for="heuristic"> Show heuristic detection</label><br>
            </div>
            <div>
              <div class="section__heading">Select annotation style &nbsp</div> 
              <div >
                <div class="div_checkbox">
                  <label><input type="radio", name="rbtn_output_selection" value="heatmap">Heatmap</label> <br>
                </div>
                <div class="div_checkbox">
                  <label><input type="radio", name="rbtn_output_selection" value="bbox">Bounding box</label> <br>
                </div>
              </div>
            </div>
            <div id="upload-section">
              <input id="upload-button" type="submit" value="Scan image" class="button" />
            </div>
          </div>
        </div>
      </form>
      
      {% endif %}

      {% if filename %}
        <div class="img_container">
              {% if context['annotation_style'] == "bbox" %}
              <img class="output_img"
                src="{{ url_for('app_router.display_bbox', filename=filename) }}"
              />
              {% endif %}
              {% if context['annotation_style'] == "heatmap" %}
              <img class="output_img"
                src="{{ url_for('app_router.display_heatmap', filename=filename) }}"
              />
              {% endif %}
              {% if context['show_heuristic'] %}
              <img class="output_img"
                src="{{ url_for('app_router.display_heuristic', filename=filename) }}"
              />
              {% endif %}

        </div>
        {% if context['mAP2'] %}
          <div class="row">
            <div class="col-25">
              <label for="subject">
                Mean Average Precision: {{ context['mAP'] }} </label
              ><br />
            </div>
          </div>
          <form id="form" method="POST" action="/feedback">
            <button type="submit">Report incorrect answer</button>
            <input
              name="report"
              style="visibility: hidden"
              value="{'filename': '{{ filename }}', 'mAP': '{{ context['prediction'] }}' }"
            />
          </form>
        {% endif %}

        <div><a href="{{ url_for('app_router.new_upload') }}" class="label_button">Upload</a> a new image</div>
    
      {% endif %}

      <button class='btnstream' id="start">Start streaming</button>
      <button class='btnstream' id="stop">Stop streaming</button>

    </section>


    <div id="container">
      <video autoplay playsinline id="videoElement"></video>
      <canvas id="canvas"></canvas>
      </div>
  
      <div class = 'video'>
          <img id="photo"  >
          <h1>video</h1>
      </div>

    <div id="messages-section">
      {% with messages = get_flashed_messages() %} {% if messages %} {% for
      message in messages %}

      <div>
        <p class="message">{{ message }}</p>
      </div>

      {% endfor %} {% endif %} {% endwith %}
    </div>

    

    






      <script src="{{ url_for('static', filename='web/js/app.js') }}"></script>


      <script type="text/javascript" charset="utf-8">

        

        var is_recording = false;
        
        var socket = io.connect(window.location.protocol + '//' + document.domain + ':' + location.port);
        socket.on('connect', function(){
            console.log("Connected...!", socket.connected)
        });


        var canvas = document.getElementById('canvas');
        const video = document.querySelector("#videoElement");
        const stream_container2 = document.getElementById("photo");
        canvas.style.width = window.innerWidth
        canvas.style.height = window.innerHeight;
        var context = canvas.getContext('2d');

        const myheight = 0;
        const mywidth = 0;
        function resize() {
        console.log('resize')
        videoRatio = video.height / video.width;
        windowRatio = window.innerHeight / window.innerWidth; /* browser size */


            if (windowRatio < videoRatio) {
                if (window.innerHeight > 50) { /* smallest video height */
                  video.height = window.innerHeight;
                } else {
                  video.height = 50;
            }
            } else {
              video.width = window.innerWidth;
            }

        };
        console.log('BEFORE RESIZE');
        console.log(video.height);
        console.log(video.width);

        resize();
        console.log('AFTER RESIZE');
        console.log(video.height);
        console.log(video.width);

        video.width = window.innerWidth;
        // video.height = window.innerHeight;
        // video.width = video.clientWidth;
        // video.height = video.clientHeight; 
        console.log(window.innerWidth)
        console.log(window.innerHeight)
        console.log(video.clientWidth)
        console.log(video.clientHeight)

        const getCameraSelection = async () => {
          const devices = await navigator.mediaDevices.enumerateDevices();
          const videoDevices = devices.filter(device => device.kind === 'videoinput');
          const options = videoDevices.map(videoDevice => {
            return `<option value="${videoDevice.deviceId}">${videoDevice.label}</option>`;
          });
          cameraOptions.innerHTML = options.join('');
        };

        document.querySelector("#start").addEventListener('click', async (e) => {
          console.log("START")
          const stream = await navigator.mediaDevices.getUserMedia({
            audio: false,
            video: {
              facingMode: 'environment'
              // facingMode: 'user'
            }
          })
          .then(function (stream) {
              video.srcObject = stream;
              video.play();
          })
          .catch(function (err0r) {

          });
          is_recording = true;
        })

        document.querySelector("#stop").addEventListener('click', async (e) => {
          const mediaStream = video.srcObject;
          const tracks = mediaStream.getTracks();
          tracks[0].stop();
          is_recording = false;
        })
    

        // if (navigator.mediaDevices.getUserMedia) {
        //     navigator.mediaDevices.getUserMedia({ video: true })
        //     .then(function (stream) {
        //         video.srcObject = stream;
        //         video.play();
        //     })
        //     .catch(function (err0r) {

        //     });
        // }

        // const FPS = 1;
        // setInterval(() => {


        //   var resizedCanvas = document.createElement("canvas");
        //   var resizedContext = resizedCanvas.getContext("2d");

        //   resizedCanvas.height = video.clientHeight;
        //   resizedCanvas.width = video.width;

        //   var canvas = document.getElementById("original-canvas");

        //   // resizedContext.drawImage(canvas, 0, 0, 200, 100);
        //   // var myResizedData = resizedCanvas.toDataURL();

        //     width=video.width;
        //     height=video.clientHeight;
        //     resizedContext.drawImage(video, 0, 0, width , height );
        //     var data = resizedCanvas.toDataURL('image/jpeg', 0.92);
        //     resizedContext.clearRect(0, 0, width,height );
        //     if(is_recording === true) {
        //       socket.emit('image', data);
        //       console.log('RECORDING')
        //     }
        //     else {
        //       console.log('NOT RECORDING')
        //     }
        // }, 5000/FPS);

        // socket.on('response_back', function(image){
        //   // var stream_container = document.getElementById("photo");
        //         // photo.setAttribute('src', "{{ url_for('app_router.display_stream') }}" );
        //         // stream_container.src = "{{ url_for('app_router.display_stream') }}";
        //       var stream_container = document.getElementById("photo");
        //       // photo.setAttribute('src', "{{ url_for('app_router.display_stream') }}" );
        //       source = "{{ url_for('app_router.display_stream') }}";
        //       timestamp = (new Date()).getTime(),
        //       newUrl = source + '?_=' + timestamp;
        //       stream_container.src = newUrl 
        // });
        // getCameraSelection();

    </script>



    <noscript>You need to enable JavaScript to view the full site.</noscript>
  </body>
</html>